// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Align {
  NONE = 0,
  LEFT = 1,
  RIGHT = 2,
  CENTER = 3
}
