// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Token } from '../pagezest-markdown/token.js';


export class BlockQuote {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BlockQuote {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBlockQuote(bb:flatbuffers.ByteBuffer, obj?:BlockQuote):BlockQuote {
  return (obj || new BlockQuote()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBlockQuote(bb:flatbuffers.ByteBuffer, obj?:BlockQuote):BlockQuote {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BlockQuote()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

tokens(index: number, obj?:Token):Token|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Token()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tokensLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startBlockQuote(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, textOffset, 0);
}

static addTokens(builder:flatbuffers.Builder, tokensOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, tokensOffset, 0);
}

static createTokensVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTokensVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endBlockQuote(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // text
  builder.requiredField(offset, 6) // tokens
  return offset;
}

static createBlockQuote(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset, tokensOffset:flatbuffers.Offset):flatbuffers.Offset {
  BlockQuote.startBlockQuote(builder);
  BlockQuote.addText(builder, textOffset);
  BlockQuote.addTokens(builder, tokensOffset);
  return BlockQuote.endBlockQuote(builder);
}
}
