// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Br {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Br {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBr(bb:flatbuffers.ByteBuffer, obj?:Br):Br {
  return (obj || new Br()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBr(bb:flatbuffers.ByteBuffer, obj?:Br):Br {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Br()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startBr(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endBr(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBr(builder:flatbuffers.Builder):flatbuffers.Offset {
  Br.startBr(builder);
  return Br.endBr(builder);
}
}
