// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Token } from '../pagezest-markdown/token.js';


export class Code {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Code {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCode(bb:flatbuffers.ByteBuffer, obj?:Code):Code {
  return (obj || new Code()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCode(bb:flatbuffers.ByteBuffer, obj?:Code):Code {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Code()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

lang():string|null
lang(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
lang(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

block():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

pre():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

tokens(index: number, obj?:Token):Token|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Token()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tokensLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startCode(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addLang(builder:flatbuffers.Builder, langOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, langOffset, 0);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, textOffset, 0);
}

static addBlock(builder:flatbuffers.Builder, block:boolean) {
  builder.addFieldInt8(2, +block, +false);
}

static addPre(builder:flatbuffers.Builder, pre:boolean) {
  builder.addFieldInt8(3, +pre, +false);
}

static addTokens(builder:flatbuffers.Builder, tokensOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, tokensOffset, 0);
}

static createTokensVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTokensVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endCode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // lang
  builder.requiredField(offset, 6) // text
  builder.requiredField(offset, 12) // tokens
  return offset;
}

static createCode(builder:flatbuffers.Builder, langOffset:flatbuffers.Offset, textOffset:flatbuffers.Offset, block:boolean, pre:boolean, tokensOffset:flatbuffers.Offset):flatbuffers.Offset {
  Code.startCode(builder);
  Code.addLang(builder, langOffset);
  Code.addText(builder, textOffset);
  Code.addBlock(builder, block);
  Code.addPre(builder, pre);
  Code.addTokens(builder, tokensOffset);
  return Code.endCode(builder);
}
}
