// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Hr {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Hr {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHr(bb:flatbuffers.ByteBuffer, obj?:Hr):Hr {
  return (obj || new Hr()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHr(bb:flatbuffers.ByteBuffer, obj?:Hr):Hr {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Hr()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startHr(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endHr(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHr(builder:flatbuffers.Builder):flatbuffers.Offset {
  Hr.startHr(builder);
  return Hr.endHr(builder);
}
}
