// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Html {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Html {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHtml(bb:flatbuffers.ByteBuffer, obj?:Html):Html {
  return (obj || new Html()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHtml(bb:flatbuffers.ByteBuffer, obj?:Html):Html {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Html()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startHtml(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, textOffset, 0);
}

static endHtml(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // text
  return offset;
}

static createHtml(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset):flatbuffers.Offset {
  Html.startHtml(builder);
  Html.addText(builder, textOffset);
  return Html.endHtml(builder);
}
}
