// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Token } from '../pagezest-markdown/token.js';


export class Image {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Image {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsImage(bb:flatbuffers.ByteBuffer, obj?:Image):Image {
  return (obj || new Image()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsImage(bb:flatbuffers.ByteBuffer, obj?:Image):Image {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Image()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

href():string|null
href(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
href(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

title():string|null
title(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
title(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

tokens(index: number, obj?:Token):Token|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Token()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tokensLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startImage(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addHref(builder:flatbuffers.Builder, hrefOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, hrefOffset, 0);
}

static addTitle(builder:flatbuffers.Builder, titleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, titleOffset, 0);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, textOffset, 0);
}

static addTokens(builder:flatbuffers.Builder, tokensOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, tokensOffset, 0);
}

static createTokensVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTokensVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endImage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 10) // tokens
  return offset;
}

static createImage(builder:flatbuffers.Builder, hrefOffset:flatbuffers.Offset, titleOffset:flatbuffers.Offset, textOffset:flatbuffers.Offset, tokensOffset:flatbuffers.Offset):flatbuffers.Offset {
  Image.startImage(builder);
  Image.addHref(builder, hrefOffset);
  Image.addTitle(builder, titleOffset);
  Image.addText(builder, textOffset);
  Image.addTokens(builder, tokensOffset);
  return Image.endImage(builder);
}
}
