// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Token } from '../pagezest-markdown/token.js';


export class ListItem {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ListItem {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsListItem(bb:flatbuffers.ByteBuffer, obj?:ListItem):ListItem {
  return (obj || new ListItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsListItem(bb:flatbuffers.ByteBuffer, obj?:ListItem):ListItem {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ListItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tokens(index: number, obj?:Token):Token|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Token()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tokensLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

task():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

checked():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startListItem(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addTokens(builder:flatbuffers.Builder, tokensOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tokensOffset, 0);
}

static createTokensVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTokensVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTask(builder:flatbuffers.Builder, task:boolean) {
  builder.addFieldInt8(1, +task, +false);
}

static addChecked(builder:flatbuffers.Builder, checked:boolean) {
  builder.addFieldInt8(2, +checked, +false);
}

static endListItem(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createListItem(builder:flatbuffers.Builder, tokensOffset:flatbuffers.Offset, task:boolean, checked:boolean):flatbuffers.Offset {
  ListItem.startListItem(builder);
  ListItem.addTokens(builder, tokensOffset);
  ListItem.addTask(builder, task);
  ListItem.addChecked(builder, checked);
  return ListItem.endListItem(builder);
}
}
