// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Space {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Space {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSpace(bb:flatbuffers.ByteBuffer, obj?:Space):Space {
  return (obj || new Space()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSpace(bb:flatbuffers.ByteBuffer, obj?:Space):Space {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Space()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startSpace(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endSpace(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSpace(builder:flatbuffers.Builder):flatbuffers.Offset {
  Space.startSpace(builder);
  return Space.endSpace(builder);
}
}
