// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Token } from '../pagezest-markdown/token.js';


export class Strong {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Strong {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStrong(bb:flatbuffers.ByteBuffer, obj?:Strong):Strong {
  return (obj || new Strong()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStrong(bb:flatbuffers.ByteBuffer, obj?:Strong):Strong {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Strong()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tokens(index: number, obj?:Token):Token|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Token()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tokensLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startStrong(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTokens(builder:flatbuffers.Builder, tokensOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tokensOffset, 0);
}

static createTokensVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTokensVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endStrong(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // tokens
  return offset;
}

static createStrong(builder:flatbuffers.Builder, tokensOffset:flatbuffers.Offset):flatbuffers.Offset {
  Strong.startStrong(builder);
  Strong.addTokens(builder, tokensOffset);
  return Strong.endStrong(builder);
}
}
