// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Align } from '../pagezest-markdown/align.js';
import { TableCell } from '../pagezest-markdown/table-cell.js';
import { TableRow } from '../pagezest-markdown/table-row.js';


export class Table {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Table {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTable(bb:flatbuffers.ByteBuffer, obj?:Table):Table {
  return (obj || new Table()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTable(bb:flatbuffers.ByteBuffer, obj?:Table):Table {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Table()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

align(index: number):Align|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

alignLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

alignArray():Int8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Int8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

header(index: number, obj?:TableCell):TableCell|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new TableCell()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

headerLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

rows(index: number, obj?:TableRow):TableRow|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new TableRow()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

rowsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startTable(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addAlign(builder:flatbuffers.Builder, alignOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, alignOffset, 0);
}

static createAlignVector(builder:flatbuffers.Builder, data:Align[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startAlignVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addHeader(builder:flatbuffers.Builder, headerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, headerOffset, 0);
}

static createHeaderVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startHeaderVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRows(builder:flatbuffers.Builder, rowsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, rowsOffset, 0);
}

static createRowsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRowsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endTable(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // align
  builder.requiredField(offset, 6) // header
  builder.requiredField(offset, 8) // rows
  return offset;
}

static createTable(builder:flatbuffers.Builder, alignOffset:flatbuffers.Offset, headerOffset:flatbuffers.Offset, rowsOffset:flatbuffers.Offset):flatbuffers.Offset {
  Table.startTable(builder);
  Table.addAlign(builder, alignOffset);
  Table.addHeader(builder, headerOffset);
  Table.addRows(builder, rowsOffset);
  return Table.endTable(builder);
}
}
