// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TableCell } from '../pagezest-markdown/table-cell.js';


export class TableRow {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TableRow {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTableRow(bb:flatbuffers.ByteBuffer, obj?:TableRow):TableRow {
  return (obj || new TableRow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTableRow(bb:flatbuffers.ByteBuffer, obj?:TableRow):TableRow {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TableRow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cells(index: number, obj?:TableCell):TableCell|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TableCell()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

cellsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startTableRow(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addCells(builder:flatbuffers.Builder, cellsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cellsOffset, 0);
}

static createCellsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCellsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endTableRow(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTableRow(builder:flatbuffers.Builder, cellsOffset:flatbuffers.Offset):flatbuffers.Offset {
  TableRow.startTableRow(builder);
  TableRow.addCells(builder, cellsOffset);
  return TableRow.endTableRow(builder);
}
}
