// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Align } from '../pagezest-markdown/align.js';
import { Token } from '../pagezest-markdown/token.js';


export class TableCell {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TableCell {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTableCell(bb:flatbuffers.ByteBuffer, obj?:TableCell):TableCell {
  return (obj || new TableCell()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTableCell(bb:flatbuffers.ByteBuffer, obj?:TableCell):TableCell {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TableCell()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

tokens(index: number, obj?:Token):Token|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Token()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tokensLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

header():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

align():Align {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : Align.NONE;
}

static startTableCell(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, textOffset, 0);
}

static addTokens(builder:flatbuffers.Builder, tokensOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, tokensOffset, 0);
}

static createTokensVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTokensVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addHeader(builder:flatbuffers.Builder, header:boolean) {
  builder.addFieldInt8(2, +header, +false);
}

static addAlign(builder:flatbuffers.Builder, align:Align) {
  builder.addFieldInt8(3, align, Align.NONE);
}

static endTableCell(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // text
  builder.requiredField(offset, 6) // tokens
  return offset;
}

static createTableCell(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset, tokensOffset:flatbuffers.Offset, header:boolean, align:Align):flatbuffers.Offset {
  TableCell.startTableCell(builder);
  TableCell.addText(builder, textOffset);
  TableCell.addTokens(builder, tokensOffset);
  TableCell.addHeader(builder, header);
  TableCell.addAlign(builder, align);
  return TableCell.endTableCell(builder);
}
}
