// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Token } from '../pagezest-markdown/token.js';


export class Text {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Text {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsText(bb:flatbuffers.ByteBuffer, obj?:Text):Text {
  return (obj || new Text()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsText(bb:flatbuffers.ByteBuffer, obj?:Text):Text {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Text()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

tokens(index: number, obj?:Token):Token|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Token()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tokensLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

escaped():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startText(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, textOffset, 0);
}

static addTokens(builder:flatbuffers.Builder, tokensOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, tokensOffset, 0);
}

static createTokensVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTokensVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addEscaped(builder:flatbuffers.Builder, escaped:boolean) {
  builder.addFieldInt8(2, +escaped, +false);
}

static endText(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // text
  return offset;
}

static createText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset, tokensOffset:flatbuffers.Offset, escaped:boolean):flatbuffers.Offset {
  Text.startText(builder);
  Text.addText(builder, textOffset);
  Text.addTokens(builder, tokensOffset);
  Text.addEscaped(builder, escaped);
  return Text.endText(builder);
}
}
