// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum TokenType {
  UNKNOWN = 0,
  HEADING = 1,
  PARAGRAPH = 2,
  LIST = 3,
  LIST_ITEM = 4,
  SPACE = 5,
  HR = 6,
  TABLE = 7,
  TEXT = 8,
  STRONG = 9,
  EM = 10,
  DEL = 11,
  LINK = 12,
  IMAGE = 13,
  HTML = 14,
  CODE = 15,
  CODESPAN = 16
}
