// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum TokenType {
  UNKNOWN = 0,
  HEADING = 1,
  PARAGRAPH = 2,
  LIST = 3,
  LIST_ITEM = 4,
  SPACE = 5,
  HR = 6,
  BR = 7,
  TABLE = 8,
  TEXT = 9,
  STRONG = 10,
  EM = 11,
  DEL = 12,
  LINK = 13,
  IMAGE = 14,
  HTML = 15,
  CODE = 16,
  CODESPAN = 17,
  BLOCKQUOTE = 18
}
