// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TokenType } from '../pagezest-markdown/token-type.js';
import { TokenValue, unionToTokenValue, unionListToTokenValue } from '../pagezest-markdown/token-value.js';


export class Token {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Token {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsToken(bb:flatbuffers.ByteBuffer, obj?:Token):Token {
  return (obj || new Token()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsToken(bb:flatbuffers.ByteBuffer, obj?:Token):Token {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Token()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():TokenType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : TokenType.UNKNOWN;
}

valueType():TokenValue {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TokenValue.NONE;
}

value<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startToken(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addType(builder:flatbuffers.Builder, type:TokenType) {
  builder.addFieldInt8(0, type, TokenType.UNKNOWN);
}

static addValueType(builder:flatbuffers.Builder, valueType:TokenValue) {
  builder.addFieldInt8(1, valueType, TokenValue.NONE);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, valueOffset, 0);
}

static endToken(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createToken(builder:flatbuffers.Builder, type:TokenType, valueType:TokenValue, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  Token.startToken(builder);
  Token.addType(builder, type);
  Token.addValueType(builder, valueType);
  Token.addValue(builder, valueOffset);
  return Token.endToken(builder);
}
}
