// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { BlockQuote } from '../pagezest-markdown/block-quote.js';
import { Br } from '../pagezest-markdown/br.js';
import { Code } from '../pagezest-markdown/code.js';
import { Codespan } from '../pagezest-markdown/codespan.js';
import { Del } from '../pagezest-markdown/del.js';
import { Em } from '../pagezest-markdown/em.js';
import { Heading } from '../pagezest-markdown/heading.js';
import { Hr } from '../pagezest-markdown/hr.js';
import { Html } from '../pagezest-markdown/html.js';
import { Image } from '../pagezest-markdown/image.js';
import { Link } from '../pagezest-markdown/link.js';
import { List } from '../pagezest-markdown/list.js';
import { ListItem } from '../pagezest-markdown/list-item.js';
import { Paragraph } from '../pagezest-markdown/paragraph.js';
import { Space } from '../pagezest-markdown/space.js';
import { Strong } from '../pagezest-markdown/strong.js';
import { Table } from '../pagezest-markdown/table.js';
import { Text } from '../pagezest-markdown/text.js';


export enum TokenValue {
  NONE = 0,
  Heading = 1,
  Paragraph = 2,
  List = 3,
  ListItem = 4,
  Space = 5,
  Hr = 6,
  Br = 7,
  Table = 8,
  Text = 9,
  Strong = 10,
  Em = 11,
  Del = 12,
  Link = 13,
  Image = 14,
  Html = 15,
  Code = 16,
  Codespan = 17,
  BlockQuote = 18
}

export function unionToTokenValue(
  type: TokenValue,
  accessor: (obj:BlockQuote|Br|Code|Codespan|Del|Em|Heading|Hr|Html|Image|Link|List|ListItem|Paragraph|Space|Strong|Table|Text) => BlockQuote|Br|Code|Codespan|Del|Em|Heading|Hr|Html|Image|Link|List|ListItem|Paragraph|Space|Strong|Table|Text|null
): BlockQuote|Br|Code|Codespan|Del|Em|Heading|Hr|Html|Image|Link|List|ListItem|Paragraph|Space|Strong|Table|Text|null {
  switch(TokenValue[type]) {
    case 'NONE': return null; 
    case 'Heading': return accessor(new Heading())! as Heading;
    case 'Paragraph': return accessor(new Paragraph())! as Paragraph;
    case 'List': return accessor(new List())! as List;
    case 'ListItem': return accessor(new ListItem())! as ListItem;
    case 'Space': return accessor(new Space())! as Space;
    case 'Hr': return accessor(new Hr())! as Hr;
    case 'Br': return accessor(new Br())! as Br;
    case 'Table': return accessor(new Table())! as Table;
    case 'Text': return accessor(new Text())! as Text;
    case 'Strong': return accessor(new Strong())! as Strong;
    case 'Em': return accessor(new Em())! as Em;
    case 'Del': return accessor(new Del())! as Del;
    case 'Link': return accessor(new Link())! as Link;
    case 'Image': return accessor(new Image())! as Image;
    case 'Html': return accessor(new Html())! as Html;
    case 'Code': return accessor(new Code())! as Code;
    case 'Codespan': return accessor(new Codespan())! as Codespan;
    case 'BlockQuote': return accessor(new BlockQuote())! as BlockQuote;
    default: return null;
  }
}

export function unionListToTokenValue(
  type: TokenValue, 
  accessor: (index: number, obj:BlockQuote|Br|Code|Codespan|Del|Em|Heading|Hr|Html|Image|Link|List|ListItem|Paragraph|Space|Strong|Table|Text) => BlockQuote|Br|Code|Codespan|Del|Em|Heading|Hr|Html|Image|Link|List|ListItem|Paragraph|Space|Strong|Table|Text|null, 
  index: number
): BlockQuote|Br|Code|Codespan|Del|Em|Heading|Hr|Html|Image|Link|List|ListItem|Paragraph|Space|Strong|Table|Text|null {
  switch(TokenValue[type]) {
    case 'NONE': return null; 
    case 'Heading': return accessor(index, new Heading())! as Heading;
    case 'Paragraph': return accessor(index, new Paragraph())! as Paragraph;
    case 'List': return accessor(index, new List())! as List;
    case 'ListItem': return accessor(index, new ListItem())! as ListItem;
    case 'Space': return accessor(index, new Space())! as Space;
    case 'Hr': return accessor(index, new Hr())! as Hr;
    case 'Br': return accessor(index, new Br())! as Br;
    case 'Table': return accessor(index, new Table())! as Table;
    case 'Text': return accessor(index, new Text())! as Text;
    case 'Strong': return accessor(index, new Strong())! as Strong;
    case 'Em': return accessor(index, new Em())! as Em;
    case 'Del': return accessor(index, new Del())! as Del;
    case 'Link': return accessor(index, new Link())! as Link;
    case 'Image': return accessor(index, new Image())! as Image;
    case 'Html': return accessor(index, new Html())! as Html;
    case 'Code': return accessor(index, new Code())! as Code;
    case 'Codespan': return accessor(index, new Codespan())! as Codespan;
    case 'BlockQuote': return accessor(index, new BlockQuote())! as BlockQuote;
    default: return null;
  }
}
